#!/usr/bin/env python3
"""DafSync Caption Sync — desktop app.

A GUI around caption_ocr_align.py: pick a lecture video, click together the
daf/amud readings it covers (tractate → page → side, in order — no typing
Sefaria refs by hand), and get an alignment JSON (with a word-level
timeline) ready to import into DafSync Studio.

Run from source:  python3 gui_app.py
Packaged builds (PyInstaller) bundle Python, OpenCV, Tesseract with the
Hebrew language data, and CustomTkinter, so nothing needs to be installed
separately.
"""

import contextlib
import json
import os
import queue
import sys
import threading
import traceback
import tkinter as tk
from tkinter import filedialog, messagebox

import customtkinter as ctk


def app_dir():
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


# Point pytesseract at the bundled Tesseract before the engine imports it.
_bundled_tess = os.path.join(app_dir(), "tesseract", "tesseract.exe")
if os.path.exists(_bundled_tess):
    os.environ["TESSDATA_PREFIX"] = os.path.join(
        app_dir(), "tesseract", "tessdata")
    import pytesseract
    pytesseract.pytesseract.tesseract_cmd = _bundled_tess

from caption_ocr_align import build_outputs, process_video
from local_server import start_server
from protocol_handler import parse_launch_payload, register_protocol_handler


# ---------------------------------------------------------------------------
# Talmud tractate/daf/amud data (generated by build_talmud_index.py from
# Sefaria's own pagination data — see that script for how it's derived)
# ---------------------------------------------------------------------------

def load_talmud_index():
    path = os.path.join(app_dir(), "talmud_index.json")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)["tractates"]


TALMUD_INDEX = load_talmud_index()
TALMUD_BY_NAME = {t["name"]: t for t in TALMUD_INDEX}
TRACTATE_NAMES = [t["name"] for t in TALMUD_INDEX]


def amudim_for_daf(entry, daf):
    """Which amudim (a/b) actually exist for this daf of this tractate."""
    sides = []
    for side in ("a", "b"):
        if daf == entry["endDaf"] and side == "b" and entry["endSide"] == "a":
            continue  # tractate ends mid-daf, no b side on the last daf
        if f"{daf}{side}" in entry["skipAmudim"]:
            continue  # a known-missing page (e.g. Nazir 33b)
        sides.append(side)
    return sides


def daf_options(entry):
    return [d for d in range(entry["startDaf"], entry["endDaf"] + 1)
            if amudim_for_daf(entry, d)]


class QueueWriter:
    def __init__(self, q):
        self.q = q

    def write(self, text):
        if text.strip():
            self.q.put(("log", text.rstrip("\n")))

    def flush(self):
        pass


CARD_PAD = {"padx": 22, "pady": 9}


class App:
    def __init__(self, root):
        self.root = root
        root.title("DafSync Caption Sync")
        root.geometry("820x780")
        root.minsize(680, 480)

        self.q = queue.Queue()
        self.worker = None
        self.readings = []  # ordered list of {ref, display}

        launch_payload = parse_launch_payload(sys.argv) or {}
        for ref in launch_payload.get("refs", []):
            self.readings.append({"ref": ref, "display": ref})
        if launch_payload:
            root.after(200, lambda: (root.deiconify(), root.lift(),
                                     root.focus_force()))

        # The whole form scrolls as one unit, so nothing gets clipped on
        # smaller screens regardless of how much content is above the fold.
        container = ctk.CTkScrollableFrame(root, fg_color="transparent")
        container.pack(fill="both", expand=True)

        header = ctk.CTkFrame(container, fg_color="transparent")
        header.pack(fill="x", padx=24, pady=(22, 4))
        ctk.CTkLabel(
            header, text="DafSync Caption Sync",
            font=ctk.CTkFont(size=23, weight="bold")
        ).pack(anchor="w")
        ctk.CTkLabel(
            header,
            text="Turn a lecture video's highlighted caption box into a "
                 "word-level Daf alignment.",
            font=ctk.CTkFont(size=13),
            text_color=("gray35", "gray70"),
        ).pack(anchor="w", pady=(2, 0))
        self.web_status_label = ctk.CTkLabel(
            header, text="", font=ctk.CTkFont(size=12),
            text_color=("gray45", "gray60"))
        self.web_status_label.pack(anchor="w", pady=(4, 0))

        self._build_reading_picker(container)
        self._build_readings_list(container)
        self._build_files_card(container)
        self._build_run_card(container)

        self.on_tractate_change(TRACTATE_NAMES[0])
        self.render_readings()
        root.after(150, self.poll_queue)
        self._start_local_server()

    def _start_local_server(self):
        server = start_server(self.q, process_video, build_outputs)
        if server is not None:
            from local_server import PORT
            self.web_status_label.configure(
                text=f"● Website sync ready — listening on 127.0.0.1:{PORT} "
                     f"for requests from mdysync.netlify.app only",
                text_color=("#2f7d3c", "#5fd576"))
        else:
            self.web_status_label.configure(
                text="○ Website sync unavailable (port already in use by "
                     "another DafSync window, or blocked)",
                text_color=("gray45", "gray60"))

    # ------------------------------------------------------------ picker UI

    def _build_reading_picker(self, root):
        card = ctk.CTkFrame(root, corner_radius=14)
        card.pack(fill="x", **CARD_PAD)

        ctk.CTkLabel(
            card, text="Add a daf reading",
            font=ctk.CTkFont(size=15, weight="bold")
        ).grid(row=0, column=0, columnspan=4, sticky="w", padx=18, pady=(16, 8))

        ctk.CTkLabel(card, text="Tractate", font=ctk.CTkFont(size=12),
                     text_color=("gray35", "gray65")
                     ).grid(row=1, column=0, sticky="w", padx=(18, 6))
        self.tractate_var = tk.StringVar(value=TRACTATE_NAMES[0])
        self.tractate_menu = ctk.CTkOptionMenu(
            card, variable=self.tractate_var, values=TRACTATE_NAMES,
            command=self.on_tractate_change, width=190)
        self.tractate_menu.grid(row=2, column=0, padx=(18, 6), pady=(0, 16),
                                 sticky="w")

        ctk.CTkLabel(card, text="Daf", font=ctk.CTkFont(size=12),
                     text_color=("gray35", "gray65")
                     ).grid(row=1, column=1, sticky="w", padx=6)
        self.daf_var = tk.StringVar()
        self.daf_menu = ctk.CTkOptionMenu(
            card, variable=self.daf_var, values=["2"],
            command=self.on_daf_change, width=90)
        self.daf_menu.grid(row=2, column=1, padx=6, pady=(0, 16), sticky="w")

        ctk.CTkLabel(card, text="Amud", font=ctk.CTkFont(size=12),
                     text_color=("gray35", "gray65")
                     ).grid(row=1, column=2, sticky="w", padx=6)
        self.amud_var = tk.StringVar(value="a")
        self.amud_seg = ctk.CTkSegmentedButton(
            card, values=["a", "b"], variable=self.amud_var, width=100)
        self.amud_seg.grid(row=2, column=2, padx=6, pady=(0, 16), sticky="w")

        self.add_btn = ctk.CTkButton(
            card, text="+  Add reading", command=self.add_reading, width=150)
        self.add_btn.grid(row=2, column=3, padx=(6, 18), pady=(0, 16),
                           sticky="w")

        card.grid_columnconfigure(4, weight=1)

    def _build_readings_list(self, root):
        card = ctk.CTkFrame(root, corner_radius=14)
        card.pack(fill="x", **CARD_PAD)

        top = ctk.CTkFrame(card, fg_color="transparent")
        top.pack(fill="x", padx=18, pady=(14, 6))
        ctk.CTkLabel(
            top, text="Readings covered, in order",
            font=ctk.CTkFont(size=15, weight="bold")
        ).pack(side="left")
        ctk.CTkButton(
            top, text="Clear all", width=84, height=26,
            fg_color="transparent", border_width=1,
            text_color=("gray20", "gray85"), command=self.clear_readings
        ).pack(side="right")

        self.readings_frame = ctk.CTkScrollableFrame(card, height=120)
        self.readings_frame.pack(fill="x", padx=18, pady=(0, 16))

    def _build_files_card(self, root):
        card = ctk.CTkFrame(root, corner_radius=14)
        card.pack(fill="x", **CARD_PAD)

        ctk.CTkLabel(
            card, text="Lecture video file", font=ctk.CTkFont(size=12),
            text_color=("gray35", "gray65")
        ).grid(row=0, column=0, sticky="w", padx=18, pady=(14, 2))
        self.video_var = tk.StringVar()
        ctk.CTkEntry(card, textvariable=self.video_var).grid(
            row=1, column=0, sticky="ew", padx=(18, 8), pady=(0, 14))
        ctk.CTkButton(card, text="Browse…", width=100,
                      command=self.pick_video).grid(
            row=1, column=1, padx=(0, 18), pady=(0, 14))

        ctk.CTkLabel(
            card, text="Output folder", font=ctk.CTkFont(size=12),
            text_color=("gray35", "gray65")
        ).grid(row=2, column=0, sticky="w", padx=18, pady=(0, 2))
        self.out_var = tk.StringVar()
        ctk.CTkEntry(card, textvariable=self.out_var).grid(
            row=3, column=0, sticky="ew", padx=(18, 8), pady=(0, 16))
        ctk.CTkButton(card, text="Browse…", width=100,
                      command=self.pick_out).grid(
            row=3, column=1, padx=(0, 18), pady=(0, 16))

        card.grid_columnconfigure(0, weight=1)

    def _build_run_card(self, root):
        card = ctk.CTkFrame(root, corner_radius=14)
        card.pack(fill="both", expand=True, padx=22, pady=(9, 20))

        self.run_btn = ctk.CTkButton(
            card, text="Sync", command=self.run, height=40,
            font=ctk.CTkFont(size=14, weight="bold"))
        self.run_btn.pack(fill="x", padx=18, pady=(16, 10))

        self.progress = ctk.CTkProgressBar(card)
        self.progress.set(0)
        self.progress.pack(fill="x", padx=18, pady=(0, 12))

        self.log = ctk.CTkTextbox(card, wrap="word", state="disabled",
                                   height=170,
                                   font=ctk.CTkFont(family="Consolas", size=12))
        self.log.pack(fill="both", expand=True, padx=18, pady=(0, 10))

        self.open_btn = ctk.CTkButton(
            card, text="Open output folder", command=self.open_out,
            state="disabled", fg_color="transparent", border_width=1,
            text_color=("gray20", "gray85"))
        self.open_btn.pack(fill="x", padx=18, pady=(0, 16))

    # --------------------------------------------------------- picker logic

    def on_tractate_change(self, name):
        entry = TALMUD_BY_NAME[name]
        options = [str(d) for d in daf_options(entry)]
        self.daf_menu.configure(values=options)
        default_daf = options[0] if options else ""
        self.daf_var.set(default_daf)
        self.on_daf_change(default_daf)

    def on_daf_change(self, daf_str):
        if not daf_str:
            self.amud_seg.configure(values=["a"])
            return
        entry = TALMUD_BY_NAME[self.tractate_var.get()]
        sides = amudim_for_daf(entry, int(daf_str)) or ["a"]
        self.amud_seg.configure(values=sides)
        if self.amud_var.get() not in sides:
            self.amud_seg.set(sides[0])

    def add_reading(self):
        tractate = self.tractate_var.get()
        daf = self.daf_var.get()
        amud = self.amud_var.get()
        if not daf:
            return
        ref = f"{tractate} {daf}{amud}"
        self.readings.append({"ref": ref, "display": ref})
        self.render_readings()

    def remove_reading(self, index):
        del self.readings[index]
        self.render_readings()

    def clear_readings(self):
        self.readings = []
        self.render_readings()

    def render_readings(self):
        for child in self.readings_frame.winfo_children():
            child.destroy()

        if not self.readings:
            ctk.CTkLabel(
                self.readings_frame,
                text="No readings added yet — pick a tractate, daf, and "
                     "amud above, then click “+ Add reading”.",
                text_color=("gray45", "gray60"),
                font=ctk.CTkFont(size=12),
            ).pack(anchor="w", pady=6, padx=4)
            return

        for i, reading in enumerate(self.readings):
            row = ctk.CTkFrame(self.readings_frame, fg_color="transparent")
            row.pack(fill="x", pady=2)
            ctk.CTkLabel(
                row, text=f"{i + 1}.  {reading['display']}",
                font=ctk.CTkFont(size=13, weight="bold")
            ).pack(side="left")
            ctk.CTkButton(
                row, text="✕", width=26, height=22,
                fg_color="transparent", border_width=0,
                text_color=("gray40", "gray70"), hover_color=("gray85", "gray25"),
                command=lambda idx=i: self.remove_reading(idx)
            ).pack(side="right")

    # ------------------------------------------------------------ file I/O

    def pick_video(self):
        path = filedialog.askopenfilename(
            title="Choose the lecture video",
            filetypes=[("Video files", "*.mp4 *.webm *.mkv *.mov *.avi"),
                       ("All files", "*.*")])
        if path:
            self.video_var.set(path)
            if not self.out_var.get():
                self.out_var.set(os.path.join(
                    os.path.dirname(path), "dafsync-output"))

    def pick_out(self):
        path = filedialog.askdirectory(title="Choose the output folder")
        if path:
            self.out_var.set(path)

    def log_line(self, text):
        self.log.configure(state="normal")
        self.log.insert("end", text + "\n")
        self.log.see("end")
        self.log.configure(state="disabled")

    def open_out(self):
        out = self.out_var.get()
        if os.path.isdir(out):
            if sys.platform == "win32":
                os.startfile(out)  # noqa: S606 - opening the user's own folder
            else:
                import subprocess
                subprocess.Popen(["xdg-open", out])

    # -------------------------------------------------------------- worker

    def run(self):
        video = self.video_var.get().strip()
        refs = [r["ref"] for r in self.readings]
        out = self.out_var.get().strip()
        if not os.path.isfile(video):
            messagebox.showerror("DafSync", "Choose a video file first.")
            return
        if not refs:
            messagebox.showerror(
                "DafSync",
                "Add at least one reading (tractate, daf, amud) using the "
                "picker above.")
            return
        if not out:
            out = os.path.join(os.path.dirname(video), "dafsync-output")
            self.out_var.set(out)

        self.run_btn.configure(state="disabled")
        self.open_btn.configure(state="disabled")
        self.progress.set(0)
        self.worker = threading.Thread(
            target=self.work, args=(video, refs, out), daemon=True)
        self.worker.start()

    def work(self, video, refs, out):
        writer = QueueWriter(self.q)
        try:
            os.makedirs(out, exist_ok=True)
            with contextlib.redirect_stdout(writer), \
                    contextlib.redirect_stderr(writer):
                canon, segments, events, duration = process_video(
                    video, refs, out_dir=out,
                    progress=lambda f: self.q.put(("progress", f)))
                if not events:
                    raise RuntimeError(
                        "No highlighted caption text could be matched. "
                        "Check that the video shows the caption box and "
                        "that the readings cover this lecture.")
                alignment, word_map = build_outputs(
                    canon, segments, events, duration, video, refs)
            a_path = os.path.join(out, "alignment.json")
            w_path = os.path.join(out, "wordmap.json")
            with open(a_path, "w", encoding="utf-8") as fh:
                json.dump(alignment, fh, ensure_ascii=False, indent=2)
            with open(w_path, "w", encoding="utf-8") as fh:
                json.dump(word_map, fh, ensure_ascii=False, indent=2)
            self.q.put(("done", (a_path, len(alignment["segments"]),
                                 len(alignment["wordTimeline"]))))
        except Exception as exc:  # surface everything to the log window
            self.q.put(("log", traceback.format_exc(limit=3)))
            self.q.put(("error", str(exc)))

    def poll_queue(self):
        try:
            while True:
                kind, payload = self.q.get_nowait()
                if kind == "log":
                    self.log_line(payload)
                elif kind == "progress":
                    self.progress.set(payload)
                elif kind == "done":
                    path, nseg, nwords = payload
                    self.progress.set(1.0)
                    self.log_line(
                        f"Done — {nseg} segments, {nwords} word spans.")
                    self.log_line(f"Alignment saved to: {path}")
                    self.log_line(
                        "Import this file in DafSync Studio with "
                        "“Import alignment”.")
                    self.run_btn.configure(state="normal")
                    self.open_btn.configure(state="normal")
                elif kind == "error":
                    self.log_line(f"Failed: {payload}")
                    self.run_btn.configure(state="normal")
                    messagebox.showerror("DafSync", payload)
        except queue.Empty:
            pass
        self.root.after(150, self.poll_queue)


def main():
    if getattr(sys, "frozen", False):
        register_protocol_handler(sys.executable)
    ctk.set_appearance_mode("system")
    ctk.set_default_color_theme("blue")
    root = ctk.CTk()
    App(root)
    root.mainloop()


if __name__ == "__main__":
    main()
